apiVersion: v1
kind: Secret
metadata:
  name: simple-file-share-auth
type: Opaque
stringData:
  SFS_DEFAULT_USERNAME: eddisonso@gmail.com
  SFS_DEFAULT_PASSWORD: pizzaeatter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-file-share-authdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-file-share-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-file-share
      tier: backend
  template:
    metadata:
      labels:
        app: simple-file-share
        tier: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: rp1
      containers:
        - name: backend
          image: eddisonso/ecloud-sfs-backend:v2
          imagePullPolicy: Always
          command: ["/app/sfs"]
          args:
            - -addr
            - 0.0.0.0:8080
            - -master
            - gfs-master:9000
            - -auth-db
            - /data/auth.db
            - -static
            - /app/frontend
          envFrom:
            - secretRef:
                name: simple-file-share-auth
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: authdb
              mountPath: /data
      volumes:
        - name: authdb
          persistentVolumeClaim:
            claimName: simple-file-share-authdb
---
apiVersion: v1
kind: Service
metadata:
  name: simple-file-share-backend
spec:
  type: NodePort
  selector:
    app: simple-file-share
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-file-share-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-file-share
      tier: frontend
  template:
    metadata:
      labels:
        app: simple-file-share
        tier: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: rp1
      containers:
        - name: frontend
          image: eddisonso/ecloud-sfs-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: simple-file-share-frontend
spec:
  type: NodePort
  selector:
    app: simple-file-share
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
