apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-file-share-api
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cloud.eddisonso.com
        - cloud-api.eddisonso.com
      secretName: eddisonso-wildcard-tls
  rules:
    - host: cloud.eddisonso.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: simple-file-share-backend
                port:
                  number: 80
          - path: /storage
            pathType: Prefix
            backend:
              service:
                name: simple-file-share-backend
                port:
                  number: 80
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: simple-file-share-backend
                port:
                  number: 80
          - path: /cluster-info
            pathType: Prefix
            backend:
              service:
                name: cluster-monitor
                port:
                  number: 80
          - path: /ws/cluster-info
            pathType: Prefix
            backend:
              service:
                name: cluster-monitor
                port:
                  number: 80
          - path: /ws/logs
            pathType: Prefix
            backend:
              service:
                name: log-service
                port:
                  number: 80
          - path: /compute
            pathType: Prefix
            backend:
              service:
                name: edd-compute
                port:
                  number: 80
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: simple-file-share-backend
                port:
                  number: 80
    - host: cloud-api.eddisonso.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-file-share-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-file-share-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - eddisonso.com
        - cloud.eddisonso.com
      secretName: eddisonso-wildcard-tls
  rules:
    - host: cloud.eddisonso.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-file-share-frontend
                port:
                  number: 80
