apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eddisonso-wildcard
  namespace: default
spec:
  secretName: eddisonso-wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: eddisonso.com
  dnsNames:
    - eddisonso.com
    - "*.eddisonso.com"
