apiVersion: v1
kind: Service
metadata:
  name: gfs-master
  labels:
    app: gfs-master
spec:
  type: NodePort
  selector:
    app: gfs-master
  ports:
    - name: master
      port: 9000          # service port (inside cluster)
      targetPort: 9000    # container port
      nodePort: 30900     # exposed LAN port (30000â€“32767)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfs-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfs-master
  template:
    metadata:
      labels:
        app: gfs-master
    spec:
      nodeSelector:
        role: master
      imagePullSecrets:
        - name: regcred
      containers:
        - name: master
          image: eddisonso/gfs-master:latest
          imagePullPolicy: Always
          command: ["./master"]
          args:
            - "-port"
            - "9000"
            - "-data"
            - "/data/master"
            - "-log-service"
            - "log-service:50051"
            - "-log-source"
            - "$(POD_NAME)"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: master-data
              mountPath: /data/master
      volumes:
        - name: master-data
          hostPath:
            path: /data/gfs

